---
- hosts: computes
  user: pi
  sudo: yes
  tasks:
  - name: start fireball
    action: fireball

- hosts: computes
  connection: fireball
  tasks:
  - name: /home is in fstab
    action: "mount name=/home src=pihead:/home fstype=nfs state=present"
  - name: /home is mounted
    action: "mount name=/home src=pihead:/home fstype=nfs state=mounted"

