---
- hosts: computes 
  user: pi
  sudo: yes
  tasks:
  - name: start fireball
    action: fireball

- hosts: computes
  connection: fireball
  tasks:
  - name: install munge key
    action: copy src=files/munge.key dest=/etc/munge/munge.key owner=munge group=munge mode=0600
    notify:
    - restart munge
  - name: munge is started
    action: service name=munge state=started
  - name: touch slurm log file
    action: command touch /var/log/slurm_jobacct.log
  - name: slurm log file ownership
    action: file dest=/var/log/slurm_jobacct.log owner=slurm state=file
  - name: slurm is configured
    action: template src=templates/slurm.conf.j2 dest=/etc/slurm-llnl/slurm.conf owner=slurm
    notify:
    - restart slurm
  - name: slurm is started
    action: service name=slurm-llnl state=started

  handlers:
    - name: restart munge
      action: service name=munge state=restarted
    - name: restart slurm
      action: service name=slurm-llnl state=restarted
