---
- hosts: headnode
  user: pi
  sudo: yes
  tasks:
  - name: start fireball
    action: fireball

- hosts: headnode 
  connection: fireball
  tasks:
  - name: dnsmasq started
    action: service name=dnsmasq state=started
  - name: configure dnsmasq
    action: template src=templates/dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
    notify:
    - restart dnsmasq

  handlers:
    - name: restart dnsmasq
      action: service name=dnsmasq state=restarted
