---
- hosts: headnode
  user: pi
  sudo: yes
  tasks:
  - name: start apache
    action: service name=apache2 state=started
  - name: configure apache
    action: template src=templates/ganglia.conf.j2 dest=/etc/apache2/conf.d/ganglia.conf
  - name: start gmond
    action: service name=ganglia-monitor state=started
  - name: start gmetad
    action: service name=gmetad state=started
