---
- hosts: headnode
  user: pi
  sudo: yes
  tasks: 
  - name: start fireball
    action: fireball

- hosts: headnode
  connection: fireball
  tasks:
  - name: copy iptables config
    action: copy src=iptables-nat.txt dest=/etc/iptables-nat.txt
  - name: restore iptables config
    action: shell iptables-restore < /etc/iptables-nat.txt
  - name: rc.local restores iptables
    action: lineinfile dest=/etc/rc.local regexp=^iptables-restore line="iptables-restore < /etc/iptables-nat.txt"
  - name: configure on forwarding
    action: lineinfile dest=/etc/sysctl.conf regexp=^net.ipv4.ip_forward line=net.ipv4.ip_forward=1
  - name: turn on forwarding
    action: shell echo 1 > /proc/sys/net/ipv4/ip_forward
